<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>Assets/voxen.ico</ApplicationIcon>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests/**/*.cs" />
    <Content Remove="Tests/**" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Blazicons.FontAwesome" Version="4.0.5" />
    <PackageReference Include="PhotinoX.Blazor" Version="5.3.3" />
    <PackageReference Include="ppy.SDL3-CS" Version="2026.1002.1" />
    <PackageReference Include="YoutubeExplode" Version="6.6.2" />
  </ItemGroup>

<ItemGroup>
    <Content Include="Assets/voxen.ico;Assets/voxen.png" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

<ItemGroup><EmbeddedResource Include="Resources/*.json" /></ItemGroup>
</Project>
