import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const code=await readFile(new URL('../wwwroot/Scripts/player-controls.js',import.meta.url),'utf8');
const {initializeVolume}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
const listeners=new Map();
globalThis.window={addEventListener:(name,fn)=>listeners.set('window:'+name,fn),removeEventListener:name=>listeners.delete('window:'+name)};
const input={value:0,style:{setProperty(){}},addEventListener:(name,fn)=>listeners.set(name,fn),removeEventListener:name=>listeners.delete(name)};
const output={textContent:''}, calls=[], releases=[];
const reference={invokeMethodAsync:(_,value)=>{calls.push(value);return new Promise(resolve=>releases.push(resolve));}};
const control=initializeVolume(input,output,reference,.7);
assert.equal(Number(input.value),70);
listeners.get('pointerdown')(); input.value=55; listeners.get('input')();
control.sync(.7); assert.equal(Number(input.value),55); assert.equal(output.textContent,'55%');
input.value=32;listeners.get('input')();input.value=21;listeners.get('input')();
listeners.get('window:pointerup')();control.sync(.55);assert.equal(Number(input.value),21);
releases.shift()();await new Promise(resolve=>setImmediate(resolve));
assert.deepEqual(calls,[.55,.21]);
releases.shift()();await new Promise(resolve=>setImmediate(resolve));control.sync(.21);
assert.equal(Number(input.value),21);control.sync(0);assert.equal(Number(input.value),0);
listeners.get('pointerdown')();input.value=55;listeners.get('input')();input.value=21;listeners.get('input')();
control.sync(0,1);assert.equal(Number(input.value),0);
releases.shift()();await new Promise(resolve=>setImmediate(resolve));
assert.deepEqual(calls,[.55,.21,.55]);assert.equal(Number(input.value),0);
control.dispose();assert.equal(listeners.size,0);
console.log('PASS Volume stays stable during dragging, coalesces pending changes, synchronizes mute, and removes listeners');
