import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source = await readFile(new URL('../wwwroot/Scripts/shortcuts.js', import.meta.url),'utf8');
const {actionFor} = await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const event = (key, options={}) => ({key, target:{closest:()=>null}, ...options});
assert.equal(actionFor(event(' ')),'toggle');
assert.equal(actionFor(event('ArrowRight')),'forward');
assert.equal(actionFor(event('k',{ctrlKey:true})),'search');
assert.equal(actionFor(event('k',{metaKey:true})),'search');
assert.equal(actionFor(event('l',{altKey:true})),'library');
assert.equal(actionFor(event('?',{shiftKey:true})),'help');
assert.equal(actionFor(event('f',{target:{closest:s=>s.startsWith('input')?{}:null}})),null);
assert.equal(actionFor(event(' ',{target:{closest:s=>s.startsWith('button')?{}:null}})),'toggle');
assert.equal(actionFor(event('Escape',{target:{closest:s=>s.startsWith('input')?{}:null}})),null);
assert.equal(actionFor(event('m',{isComposing:true})),null);
assert.equal(actionFor(event('ArrowUp',{repeat:true})),null);
assert.equal(actionFor(event('f',{ctrlKey:true})),null);
assert.equal(actionFor(event('f',{defaultPrevented:true})),null);
console.log('PASS keyboard shortcuts preserve typing, native button behavior, composition, modifiers and repeat guards');
